# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface_flash_all.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_All(object):
    def setupUi(self, Form_All):
        Form_All.setObjectName("Form_All")
        Form_All.resize(790, 410)
        self.tabWidget = QtWidgets.QTabWidget(Form_All)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 781, 401))
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton_refreshAll = QtWidgets.QPushButton(self.tab)
        self.pushButton_refreshAll.setGeometry(QtCore.QRect(320, 330, 121, 25))
        self.pushButton_refreshAll.setObjectName("pushButton_refreshAll")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 421, 151))
        self.groupBox.setObjectName("groupBox")
        self.listWidget_firmware = QtWidgets.QListWidget(self.groupBox)
        self.listWidget_firmware.setGeometry(QtCore.QRect(30, 30, 231, 111))
        self.listWidget_firmware.setObjectName("listWidget_firmware")
        self.pushButton_firmware_refresh = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_firmware_refresh.setGeometry(QtCore.QRect(300, 100, 89, 25))
        self.pushButton_firmware_refresh.setObjectName("pushButton_firmware_refresh")
        self.pushButton_next = QtWidgets.QPushButton(self.tab)
        self.pushButton_next.setGeometry(QtCore.QRect(670, 330, 89, 25))
        self.pushButton_next.setStyleSheet("background : rgb(78, 154, 6)")
        self.pushButton_next.setObjectName("pushButton_next")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 130, 751, 191))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_carte_1 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_carte_1.setGeometry(QtCore.QRect(10, 20, 161, 161))
        self.groupBox_carte_1.setObjectName("groupBox_carte_1")
        self.listWidget_com_1 = QtWidgets.QListWidget(self.groupBox_carte_1)
        self.listWidget_com_1.setGeometry(QtCore.QRect(10, 40, 131, 101))
        self.listWidget_com_1.setObjectName("listWidget_com_1")
        self.groupBox_carte_4 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_carte_4.setGeometry(QtCore.QRect(580, 20, 161, 161))
        self.groupBox_carte_4.setObjectName("groupBox_carte_4")
        self.listWidget_com_4 = QtWidgets.QListWidget(self.groupBox_carte_4)
        self.listWidget_com_4.setGeometry(QtCore.QRect(20, 30, 121, 111))
        self.listWidget_com_4.setObjectName("listWidget_com_4")
        self.groupBox_carte_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_carte_3.setGeometry(QtCore.QRect(390, 20, 161, 161))
        self.groupBox_carte_3.setObjectName("groupBox_carte_3")
        self.listWidget_com_3 = QtWidgets.QListWidget(self.groupBox_carte_3)
        self.listWidget_com_3.setGeometry(QtCore.QRect(10, 40, 131, 101))
        self.listWidget_com_3.setObjectName("listWidget_com_3")
        self.groupBox_carte_2 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_carte_2.setGeometry(QtCore.QRect(200, 20, 161, 161))
        self.groupBox_carte_2.setObjectName("groupBox_carte_2")
        self.listWidget_com_2 = QtWidgets.QListWidget(self.groupBox_carte_2)
        self.listWidget_com_2.setGeometry(QtCore.QRect(10, 40, 131, 101))
        self.listWidget_com_2.setObjectName("listWidget_com_2")
        self.label_error = QtWidgets.QLabel(self.tab)
        self.label_error.setGeometry(QtCore.QRect(450, 90, 321, 20))
        self.label_error.setStyleSheet("color : rgb(239, 41, 41)")
        self.label_error.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error.setObjectName("label_error")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton_flashAll = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_flashAll.setGeometry(QtCore.QRect(670, 310, 101, 41))
        self.pushButton_flashAll.setStyleSheet("background : rgb(78, 154, 6)")
        self.pushButton_flashAll.setObjectName("pushButton_flashAll")
        self.frame_1 = QtWidgets.QFrame(self.tab_2)
        self.frame_1.setGeometry(QtCore.QRect(20, 0, 611, 91))
        self.frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_1.setObjectName("frame_1")
        self.listWidget_flash_carte_1 = QtWidgets.QListWidget(self.frame_1)
        self.listWidget_flash_carte_1.setGeometry(QtCore.QRect(170, 1, 441, 91))
        self.listWidget_flash_carte_1.setObjectName("listWidget_flash_carte_1")
        self.widget = QtWidgets.QWidget(self.frame_1)
        self.widget.setGeometry(QtCore.QRect(10, 0, 161, 91))
        self.widget.setObjectName("widget")
        self.pushButton_Flash_1 = QtWidgets.QPushButton(self.widget)
        self.pushButton_Flash_1.setGeometry(QtCore.QRect(30, 40, 89, 41))
        self.pushButton_Flash_1.setStyleSheet("background : rgb(138, 226, 52)")
        self.pushButton_Flash_1.setObjectName("pushButton_Flash_1")
        self.label_flash_1 = QtWidgets.QLabel(self.widget)
        self.label_flash_1.setGeometry(QtCore.QRect(-10, 0, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_flash_1.setFont(font)
        self.label_flash_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_flash_1.setObjectName("label_flash_1")
        self.label_finish_1 = QtWidgets.QLabel(self.widget)
        self.label_finish_1.setGeometry(QtCore.QRect(0, 20, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_finish_1.setFont(font)
        self.label_finish_1.setStyleSheet("color : rgb(78, 154, 6)")
        self.label_finish_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_finish_1.setObjectName("label_finish_1")
        self.frame_2 = QtWidgets.QFrame(self.tab_2)
        self.frame_2.setGeometry(QtCore.QRect(20, 90, 611, 91))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.listWidget_flash_carte_22 = QtWidgets.QListWidget(self.frame_2)
        self.listWidget_flash_carte_22.setGeometry(QtCore.QRect(170, 0, 441, 91))
        self.listWidget_flash_carte_22.setObjectName("listWidget_flash_carte_22")
        self.widget_3 = QtWidgets.QWidget(self.frame_2)
        self.widget_3.setGeometry(QtCore.QRect(10, 0, 161, 91))
        self.widget_3.setObjectName("widget_3")
        self.pushButton_Flash_22 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_Flash_22.setGeometry(QtCore.QRect(30, 40, 89, 41))
        self.pushButton_Flash_22.setStyleSheet("background : rgb(138, 226, 52)")
        self.pushButton_Flash_22.setObjectName("pushButton_Flash_22")
        self.label_flash_2 = QtWidgets.QLabel(self.widget_3)
        self.label_flash_2.setGeometry(QtCore.QRect(-10, 0, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_flash_2.setFont(font)
        self.label_flash_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_flash_2.setObjectName("label_flash_2")
        self.label_finish_22 = QtWidgets.QLabel(self.widget_3)
        self.label_finish_22.setGeometry(QtCore.QRect(0, 20, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_finish_22.setFont(font)
        self.label_finish_22.setStyleSheet("color : rgb(78, 154, 6)")
        self.label_finish_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_finish_22.setObjectName("label_finish_22")
        self.frame_3 = QtWidgets.QFrame(self.tab_2)
        self.frame_3.setGeometry(QtCore.QRect(20, 180, 611, 91))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.listWidget_flash_carte_33 = QtWidgets.QListWidget(self.frame_3)
        self.listWidget_flash_carte_33.setGeometry(QtCore.QRect(170, 0, 441, 91))
        self.listWidget_flash_carte_33.setObjectName("listWidget_flash_carte_33")
        self.widget_4 = QtWidgets.QWidget(self.frame_3)
        self.widget_4.setGeometry(QtCore.QRect(10, 0, 161, 91))
        self.widget_4.setObjectName("widget_4")
        self.pushButton_Flash_33 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_Flash_33.setGeometry(QtCore.QRect(30, 40, 89, 41))
        self.pushButton_Flash_33.setStyleSheet("background : rgb(138, 226, 52)")
        self.pushButton_Flash_33.setObjectName("pushButton_Flash_33")
        self.label_flash_3 = QtWidgets.QLabel(self.widget_4)
        self.label_flash_3.setGeometry(QtCore.QRect(-10, 0, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_flash_3.setFont(font)
        self.label_flash_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_flash_3.setObjectName("label_flash_3")
        self.label_finish_33 = QtWidgets.QLabel(self.widget_4)
        self.label_finish_33.setGeometry(QtCore.QRect(0, 20, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_finish_33.setFont(font)
        self.label_finish_33.setStyleSheet("color : rgb(78, 154, 6)")
        self.label_finish_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_finish_33.setObjectName("label_finish_33")
        self.frame_4 = QtWidgets.QFrame(self.tab_2)
        self.frame_4.setGeometry(QtCore.QRect(20, 270, 611, 91))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.listWidget_flash_carte_44 = QtWidgets.QListWidget(self.frame_4)
        self.listWidget_flash_carte_44.setGeometry(QtCore.QRect(170, 1, 441, 90))
        self.listWidget_flash_carte_44.setObjectName("listWidget_flash_carte_44")
        self.widget_5 = QtWidgets.QWidget(self.frame_4)
        self.widget_5.setGeometry(QtCore.QRect(10, 0, 161, 91))
        self.widget_5.setObjectName("widget_5")
        self.pushButton_Flash_44 = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_Flash_44.setGeometry(QtCore.QRect(30, 40, 89, 41))
        self.pushButton_Flash_44.setStyleSheet("background : rgb(138, 226, 52)")
        self.pushButton_Flash_44.setObjectName("pushButton_Flash_44")
        self.label_flash_4 = QtWidgets.QLabel(self.widget_5)
        self.label_flash_4.setGeometry(QtCore.QRect(-10, 0, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_flash_4.setFont(font)
        self.label_flash_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_flash_4.setObjectName("label_flash_4")
        self.label_finish_44 = QtWidgets.QLabel(self.widget_5)
        self.label_finish_44.setGeometry(QtCore.QRect(0, 20, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_finish_44.setFont(font)
        self.label_finish_44.setStyleSheet("color : rgb(78, 154, 6)")
        self.label_finish_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_finish_44.setObjectName("label_finish_44")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Form_All)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form_All)

    def retranslateUi(self, Form_All):
        _translate = QtCore.QCoreApplication.translate
        Form_All.setWindowTitle(_translate("Form_All", "Flash ESP"))
        self.pushButton_refreshAll.setText(_translate("Form_All", "Tout rafraichir"))
        self.groupBox.setTitle(_translate("Form_All", "Firmware"))
        self.pushButton_firmware_refresh.setText(_translate("Form_All", "Rafraichir"))
        self.pushButton_next.setText(_translate("Form_All", "Suivant"))
        self.groupBox_carte_1.setTitle(_translate("Form_All", "Carte 1"))
        self.groupBox_carte_4.setTitle(_translate("Form_All", "Carte 4"))
        self.groupBox_carte_3.setTitle(_translate("Form_All", "Carte 3"))
        self.groupBox_carte_2.setTitle(_translate("Form_All", "Carte 2"))
        self.label_error.setText(_translate("Form_All", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form_All", "Configuration"))
        self.pushButton_flashAll.setText(_translate("Form_All", "Flash All"))
        self.pushButton_Flash_1.setText(_translate("Form_All", "Flash"))
        self.label_flash_1.setText(_translate("Form_All", "Carte 1"))
        self.label_finish_1.setText(_translate("Form_All", "Terminer"))
        self.pushButton_Flash_22.setText(_translate("Form_All", "Flash"))
        self.label_flash_2.setText(_translate("Form_All", "Carte 2"))
        self.label_finish_22.setText(_translate("Form_All", "Terminer"))
        self.pushButton_Flash_33.setText(_translate("Form_All", "Flash"))
        self.label_flash_3.setText(_translate("Form_All", "Carte 3"))
        self.label_finish_33.setText(_translate("Form_All", "Terminer"))
        self.pushButton_Flash_44.setText(_translate("Form_All", "Flash"))
        self.label_flash_4.setText(_translate("Form_All", "Carte 4"))
        self.label_finish_44.setText(_translate("Form_All", "Terminer"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form_All", "Flash"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_All = QtWidgets.QWidget()
    ui = Ui_Form_All()
    ui.setupUi(Form_All)
    Form_All.show()
    sys.exit(app.exec_())
